name: Cypress mocked e2e tests

on:
  push:
    branches-ignore: [ "staging", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
    - REACT_APP_USE_MOCKS: true
    - BROWSER: none
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cypress run
      uses: cypress-io/github-action@v4.2.1
      with:
        command: npm run ci
