name: Cypress mocked e2e tests

on:
  push:
    branches-ignore: [ "staging", "main" ]

jobs:
  mocked-test:
    runs-on: ubuntu-latest
    env:
      REACT_APP_URL: ${{ secrets.LOCAL_URL }}
      REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      REACT_APP_EMAIL: ${{ secrets.EMAIL }}
      REACT_APP_EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      REACT_APP_USE_MOCKS: true
      BROWSER: none
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.1
    - run: node -v
    - name: Cypress run
      uses: cypress-io/github-action@v4.2.1
      with:
        command: npm run ci
    - name: Archive test screenshots
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: cypress/screenshots/**/*.*
    - name: Archive test videos
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: videos
        path: cypress/videos/**/*.*
